# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a332894b1ddb93b58934928c72ad6b8b3f21d666316dc9a1ff24cd961b1de3759946ce2410d019d071eaedf84c3078087c5c14af17e4130ffc436997e4dd2974

test:
  secret_key_base: 2fe51d1e13e279b7ff4cc165420478a5e5284096595b655b29f6f267941c2e039f200aacae845ace6f64f2298998b216f0adee9e7b77872ce44590029dc124be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
